# Shows notifications on detection.
notifications:
  # Do you want to enable notifications?
  enabled: true

  # Placeholders: %player% %ping%
  # %check% gets replaced dynamically by the check.
  message: "&c&lEF: &e%player% &f| &6%check% &f| &c%ping%ms"

# Prevents exploits with custompayload packets.
custompayload:
  # Do you want to enable this module?
  enabled: true

  # Maximum custom payload packets that can be sent per second.
  limit:
    normal: 6
    # Increase if you have false positives in BungeeCord.
    other: 400

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 1

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []

# Checks if players have a invalid UUID.
uuidspoof:
  # Do you want to enable this module?
  enabled: true

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 1

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []

# Checks if players try to crash/exploit the server with commands.
commands:
  # Do you want to enable this module?
  enabled: true

  # Commands to detect.
  commands:
    - "//calc"
    - "//calculate"
    - "//eval"
    - "//evaluate"
    - "//solve"
    - "/hd readtext"
    - "/holographicdisplays readtext"
    - "/pex promote"
    - "/pex demote"
    - "/promote"
    - "/demote"
    - "/execute"

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 1

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []

##############################
#         Bukkit only        #
##############################

# Recreates items obtained in creative to remove invalid tags, enchants, etc.
itemsfix:
  # Do you want to enable this module?
  enabled: true

# Limits packets with ProtocolLib to avoid exploits.
packets:
  # Do you want to enable this module?
  enabled: true

  # If a packet exceds this size it will be cancelled.
  max_size: 16384

  # Max packets per second.
  # The ones ending with WRONG are impossible packets.
  # WRONG packets are recommended to set to 1 but it can cause issues with laggy players.
  limits:
    ABILITIES: 250
    ARM_ANIMATION: 80
    BLOCK_DIG: 120
    BLOCK_PLACE: 80
    BLOCK_PLACE_BOOKS: 5
    BLOCK_PLACE_WRONG: 20
    ENTITY_ACTION: 60
    KEEP_ALIVE: 5
    POSITION: 250
    SET_CREATIVE_SLOT: 200
    SET_CREATIVE_SLOT_WRONG: 1
    TAB_COMPLETE: 50
    UPDATE_SIGN: 8
    USE_ENTITY: 80
    USE_ITEM: 80
    WINDOW_CLICK: 80
    WINDOW_CLICK_WRONG: 15

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 2

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []

# Prevents invalid book creation.
books:
  enabled: true

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 1

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []

# Prevents invalid sign creation.
signs:
  enabled: true

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 1

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []

# Prevents duplication with Signs/Books by cancelling characters of 3 or more bytes long.
duplication:
  # Do you want to enable this module?
  enabled: true

  # Maximum bytes allowed per character.
  # Common keyboard characters are 1 byte long.
  # Characters with tildes are 2 bytes long.
  # Chinese characters are 3 bytes long.
  # Emojis are 4 bytes long.
  max_bytes: 2

  # Punishes players that get detected by the check.
  punishment:
    # Do you want to punish player when they get detected?
    enabled: true

    # How many times should a player be detected to be punished
    threshold: 1

    # Kick the player on detection?
    kick: true

    # Placeholders: %player%
    commands: []